name: Apply DB migrations

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to use (branch, tag, or SHA)'
        type: string
        required: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
      - uses: oven-sh/setup-bun@v2
      - name: Install server workspace only
        run: bun install --frozen-lockfile
      - name: Drizzle push
        working-directory: apps/server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun run db:push
